### PR TITLE
Added past event details page and past events page

### PR DESCRIPTION
**Pull request by AkhileshManda**
Made pre-existing details page and new pages responsive to landscape mode

please check and let me know if anything needs to be updated
@vikiwarrior

### CODE REVIEW

**Comment by AkhileshManda** [comment]
Let me know if you want me to add screen shots sir

**Comment by mrcchef** [comment]
@AkhileshManda I will review your PR by today afternoon. Just a bit busy :)

**Comment by mrcchef** [comment]
@AkhileshManda Please send me some screenshots of your work.

**Comment by mrcchef** [comment]
@AkhileshManda 
I found two things that need to be fixed.
1) Pixels are overflowing in the More Details section of event details, the "Rate Now" is overflowing
2) When I open the "more detail" screen and then rotate it in landscape mode, an annoying empty container is there. You can also observe this in the image attached.

These two things need to be fixed!!

WhatsApp Image 2021-10-09 at 16 24 13 (1)
WhatsApp Image 2021-10-09 at 16 24 13

**Comment by AkhileshManda** [comment]
Added necessary commits pls check

**Comment by mrcchef** [comment]
@AkhileshManda 
Merged!!

**Pull request merged**
